AddModel("Cone", "cone_flat.obj", "land.jpg", "0,0,0", "90")
AddModel("Cylinder", "cylinder_flat.obj", "bricks.jpg", "5,0,0", "45")
AddModel("Sphere", "sphere_smooth.obj", "land.jpg", "10,0,0", "168")
AddModel("Mockup","mockup.obj", "bricks.jpg", "15,0,0", "50")
AddModel("Suzanna","suzanna_flat.obj", "land.jpg", "20,0,0", "180")
AddModel("Teapot", "teapot_smooth.obj", "bricks.jpg", "25,0,0", "405")
