--If needed every Text needs an ID
--(Player enters/Game starts)
ID("reception")--(Player starts at the reception desk)
Text(1,"Oh... OH! Hello! Hello down there! Or well, in there, in me, uhm. Oh this is awkward.",10)
Text(2,"Well, uhm, are you the new Curator who's bought the museum?",10)
Text(3,"Where are my manners? I am your humble artificial tour guide, A.L.F.R.E.D, (Artificial Listing Framework for Research Education and Distribution).",10)
Delay(5) --(Pauses for a moment)
Text(4,"Oh right, even if you could reply I wouldn't hear you. Right well, welcome to The Ad Finem Historiae Museum, an innovative place of learning, history and technology! Did you know you're our first guest in over 7532 days! Exciting!",10)
Text(5,"Now, if you look towards the reception desk, you should see a F.R.E.D (Friendly Reading and Educational Device). Haha, get it? F.R.E.D and I'm A.L.F.R.E.D. Running joke, so hehe uh, put it on.",10)
Freedom() --(Player unfreezes)

ID("NotPickUpFred")--(If player does not pick up F.R.E.D)
Text(6,"So, uhm, right there. On the desk... yep.",5)
Text(7,"Going to stand there? Cool, cool... yep.",5)
Text(8,"Just waiting, here, doing nothing... yep.",5)
ID("PickupFred") --(Trigger: Player picks up F.R.E.D)
Text(9,"Ah fantastic! Think of F.R.E.D as a part of me, because he's F.R.E.D and I'm A.L.F.R.E.D, (laughs awkwardly)",10)
Text(10,"If you use F.R.E.D, you will be able to see the museum repository.",10)
Text(11,"If you want to get the museum up and running again, you must empty out the storage and return all the exhibits back to normal.",10)

Text(12,"Now thanks to F.R.E.D, I'll be with you through your whole trip through history! Let's start off at the beginning! Make your way to the Prehistoric exhibit!",7)
ID("TriggerExhibit")--(If player does not trigger exhibit)
Text(13,"So, we are just going to appreciate the reception... sure cool.",5)
Text(14,"If you look up really closely at the ceiling, you can see a a unique crack made by... oh, never mind, they fixed it. Oh.",6)
Music("ElevatorMusic")
Text("*Elevator music plays*",5)
ID("TowardsExhibit") --(Trigger: Player walks up to the exhibit door)
Text(15,"Right, now this may look like an ordinary door to you, but in fact it's THE most advanced door in history! That says a lot because we are in a history museum (laughs awkwardly)",8)
Text(16,"Activate your F.R.E.D and you'll see something amazing.",5)
ID("NotTriggerFred")--(If player does not trigger F.R.E.D)
Text(17,"It's really amazing",3)
Text(18,"You won't regret it! Trust me.",4)
Text(19,"It's got *Friendly* in the name.",4)

ID("TriggerFred") --(Trigger: Player uses F.R.E.D)
Text(20,"A simple lock requiring common sense, I present a maze! Get all those black squares in one go and the door *should* open!",6)
ID("CompleteFirstDoorMaze") --(Trigger: Player completes the maze)
Text(21,"Fantastic! Now, stand back a moment and... Open!",4)
Delay(5)--(Door does not open)
Text(22,"Ahem, open. OPEN. Open saysame! *sigh* One moment please",5)
Music("Hammers")--Hammers and drills SFX)
Music("openDoor") ID("DoorOpen")--(Door opens)
Text(23,"Ah, there we go. Welcome to the world of before!",4)
--Load("Prehistoric")--(Player enters Prehistoric exhibit)